psql -U postgres
12345

CREATE DATABASE blog;

\c blog

SET NAMES 'UTF8';

SET CLIENT_ENCODING TO 'UTF8';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE posts (
id BIGSERIAL NOT NULL PRIMARY KEY,
title VARCHAR(115) NOT NULL,
description VARCHAR(250),
body TEXT NOT NULL,
user_id BIGINT NOT NULL
);

CREATE TABLE users (
id BIGSERIAL NOT NULL PRIMARY KEY,
nickname VARCHAR(50) NOT NULL,
hash VARCHAR (250) NOT NULL
);
